import React,{useEffect,useRef,useState}from"react";
import{View,Text,StyleSheet,Pressable,ScrollView,Dimensions}from"react-native";
import{StatusBar}from"expo-status-bar"; import*as Device from"expo-device"; import*as Battery from"expo-battery"; import*as ImagePicker from"expo-image-picker";
import{LinearGradient}from"expo-linear-gradient"; import{Ionicons}from"@expo/vector-icons";
const W=Dimensions.get("window").width, A="#8A63FF";
function Graph({v=[]}:{v?:number[]}){let x=v.slice(-32);if(x.length<2)return <View style={{height:42}}/>;let mn=Math.min(...x),mx=Math.max(...x),sp=Math.max(1,mx-mn);return <View style={s.graph}>{x.map((n,i)=><View key={i} style={{width:Math.max(2,(W-86)/32-2),height:7+(n-mn)/sp*34,borderRadius:4,backgroundColor:A,opacity:.35+i/45}}/>)}</View>}
function Card(p:any){return <View style={[s.card,p.style]}>{p.children}</View>}
function Metric(p:any){return <Card style={{flex:1}}><Ionicons name={p.icon} size={19} color={A}/><Text style={s.muted}>{p.title}</Text><Text style={s.metric}>{p.value}</Text></Card>}
export default function App(){
 const[fps,setFps]=useState(60),[ft,setFt]=useState(16.7),[hist,setHist]=useState<number[]>([]),[ram,setRam]=useState("N/A"),[bat,setBat]=useState("N/A"),[charging,setCharging]=useState(false),[boost,setBoost]=useState(false),[tab,setTab]=useState("Home"),[sec,setSec]=useState(0);const last=useRef(0);
 useEffect(()=>{let id=0;const loop=(t:number)=>{if(last.current){let d=t-last.current;if(d>0&&d<1000){let f=Math.min(240,1000/d);setFps(Math.round(f));setFt(Math.round(d*10)/10);setHist(h=>[...h,f].slice(-48))}}last.current=t;id=requestAnimationFrame(loop)};id=requestAnimationFrame(loop);return()=>cancelAnimationFrame(id)},[]);
 useEffect(()=>{let id=setInterval(async()=>{setSec(x=>x+1);try{setBat(Math.round((await Battery.getBatteryLevelAsync())*100)+"%");setCharging((await Battery.getBatteryStateAsync())===Battery.BatteryState.CHARGING)}catch{}},1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(Device.totalMemory)setRam((Device.totalMemory/1073741824).toFixed(1)+" GB")},[]);
 const photo=async()=>{await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],quality:1})};
 const nav=[["Home","grid"],["Monitor","pulse"],["Gaming","game-controller"],["Audio","musical-notes"],["Settings","settings"]];
 return <LinearGradient colors={["#060609","#101017","#060609"]} style={{flex:1}}><StatusBar style="light"/><ScrollView contentContainerStyle={s.page}>
 <View style={s.header}><View><Text style={s.brand}>NOVA<Text style={{color:A}}>//</Text>CORE</Text><Text style={s.sub}>PERFORMANCE CONTROL CENTER</Text></View><View style={s.live}><View style={s.dot}/><Text style={s.liveT}>LIVE</Text></View></View>
 {tab==="Home"&&<><Card style={s.hero}><View style={{flex:1}}><Text style={s.kicker}>SYSTEM STATUS</Text><Text style={s.big}>{fps}<Text style={s.unit}> FPS</Text></Text><Text style={s.muted}>{ft} ms frame time</Text></View><View style={s.core}><View style={s.core2}><Ionicons name="flash" size={28} color={A}/></View></View></Card><View style={s.row}><Metric title="RAM" value={ram} icon="hardware-chip"/><Metric title="BATTERY" value={bat} icon={charging?"battery-charging":"battery-half"}/></View><Card><Text style={s.title}>FPS TELEMETRY</Text><Graph v={hist}/><Text style={s.muted}>Session {Math.floor(sec/60)}m {sec%60}s</Text></Card><Pressable onPress={()=>setBoost(!boost)} style={s.boost}><Ionicons name={boost?"rocket":"flash"} size={23} color={A}/><View style={{flex:1}}><Text style={s.boostTitle}>{boost?"PERFORMANCE ACTIVE":"SAFE GAME BOOST"}</Text><Text style={s.muted}>Reduces NOVA monitoring/visual overhead</Text></View><View style={[s.switch,{backgroundColor:boost?A:"#28282F"}]}><View style={s.knob}/></View></Pressable></>}
 {tab==="Monitor"&&<Card><Text style={s.title}>LIVE TELEMETRY</Text><Text style={s.muted}>FPS</Text><Text style={s.metric}>{fps} fps</Text><Graph v={hist}/><Text style={s.muted}>PING</Text><Text style={s.metric}>N/A</Text><Text style={s.small}>Universal game-server ping is not exposed by Expo Go. A native target-based implementation is needed.</Text><Text style={s.muted}>THERMAL</Text><Text style={s.metric}>N/A</Text><Text style={s.small}>CPU/GPU temperature is not universally exposed in Expo Go. Native Android thermal APIs are device-dependent.</Text></Card>}
 {tab==="Gaming"&&<><Card style={s.game}><Text style={s.kicker}>GAME SESSION</Text><Text style={s.big}>{boost?"ACTIVE":"READY"}</Text><Text style={s.muted}>Safe mode; no root, fake RAM, fake temperature, governor hacks, or GPU overclock.</Text><Pressable onPress={()=>setBoost(!boost)} style={s.primary}><Text style={s.primaryT}>{boost?"STOP BOOST":"START BOOST"}</Text></Pressable></Card><Card><Text style={s.title}>SESSION</Text><Text style={s.muted}>{fps} FPS • {ft} ms</Text></Card></>}
 {tab==="Audio"&&<><Card><Text style={s.title}>AUDIO CENTER</Text><Text style={s.muted}>Audio-only ambience is the low-resource option.</Text><Text style={s.small}>Persistent background playback needs a native Development Build.</Text></Card><Card><Text style={s.title}>BACKGROUND STUDIO</Text><Pressable onPress={photo} style={s.secondary}><Ionicons name="image" size={18} color={A}/><Text style={s.secondaryT}>CHOOSE PHOTO</Text></Pressable></Card></>}
 {tab==="Settings"&&<><Card><Text style={s.title}>THEMES</Text><View style={s.themes}><View style={[s.theme,{backgroundColor:"#08080A"}]}/><View style={[s.theme,{backgroundColor:"#EFE6D4"}]}/><View style={[s.theme,{backgroundColor:"#FFF"}]}/></View></Card><Card><Text style={s.title}>DEVICE</Text><Text style={s.info}>Manufacturer <Text style={s.value}>{Device.manufacturer||"N/A"}</Text></Text><Text style={s.info}>Model <Text style={s.value}>{Device.modelName||"N/A"}</Text></Text><Text style={s.info}>Android <Text style={s.value}>{Device.osVersion||"N/A"}</Text></Text><Text style={s.info}>RAM <Text style={s.value}>{ram}</Text></Text></Card><Card><Text style={s.title}>SAFETY</Text><Text style={s.small}>Unavailable telemetry is shown as N/A. Android restrictions are respected.</Text></Card></>}
 <View style={s.nav}>{nav.map(([n,i])=><Pressable key={n} onPress={()=>setTab(n)} style={s.navI}><Ionicons name={i as any} size={20} color={tab===n?A:"#777780"}/><Text style={[s.navT,{color:tab===n?A:"#777780"}]}>{n}</Text></Pressable>)}</View>
 </ScrollView></LinearGradient>}
const s=StyleSheet.create({page:{padding:18,paddingBottom:105},header:{marginTop:12,marginBottom:18,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},brand:{fontSize:25,fontWeight:"900",letterSpacing:1,color:"#F5F5F7"},sub:{fontSize:9,letterSpacing:2,color:"#777780",marginTop:4},live:{flexDirection:"row",gap:6,alignItems:"center",backgroundColor:"#121217",padding:7,borderRadius:18},dot:{width:7,height:7,borderRadius:9,backgroundColor:"#70F0A5"},liveT:{fontSize:9,color:"#AAA"},card:{backgroundColor:"#111116",borderWidth:1,borderColor:"#22222B",borderRadius:20,padding:17,marginBottom:12},hero:{minHeight:155,flexDirection:"row",alignItems:"center"},kicker:{fontSize:10,letterSpacing:2,color:"#777780"},big:{fontSize:47,fontWeight:"900",color:"#F5F5F7",marginTop:5},unit:{fontSize:13,color:"#8A8A94"},muted:{fontSize:12,color:"#777780",marginTop:4},small:{fontSize:11,color:"#6E6E78",lineHeight:17,marginTop:10},metric:{fontSize:19,fontWeight:"800",color:"#E7E7EB",marginTop:4},value:{fontWeight:"800",color:"#E7E7EB"},row:{flexDirection:"row",gap:12},core:{width:95,height:95,borderRadius:100,borderWidth:1,borderColor:"#272733",alignItems:"center",justifyContent:"center"},core2:{width:70,height:70,borderRadius:100,borderWidth:2,borderColor:A,alignItems:"center",justifyContent:"center"},title:{fontSize:12,fontWeight:"800",letterSpacing:1,color:"#D9D9E0",marginBottom:11},graph:{height:45,flexDirection:"row",alignItems:"flex-end",gap:2,marginVertical:8},boost:{flexDirection:"row",alignItems:"center",gap:12,padding:16,borderRadius:20,borderWidth:1,borderColor:"#262631",marginBottom:12},boostTitle:{fontSize:13,fontWeight:"800",color:"#EDEDF2"},switch:{width:43,height:25,borderRadius:20,padding:3,justifyContent:"center"},knob:{width:19,height:19,borderRadius:20,backgroundColor:"#FFF",alignSelf:"flex-end"},game:{minHeight:190,justifyContent:"center"},primary:{backgroundColor:A,padding:15,borderRadius:15,alignItems:"center",marginTop:15},primaryT:{color:"#FFF",fontWeight:"900",letterSpacing:1},secondary:{flexDirection:"row",gap:10,alignItems:"center",justifyContent:"center",padding:15,borderRadius:15,borderWidth:1,borderColor:"#292933",marginTop:12},secondaryT:{color:"#E6E6EB",fontWeight:"800"},themes:{flexDirection:"row",gap:14},theme:{width:55,height:55,borderRadius:16,borderWidth:1,borderColor:"#333"},info:{color:"#777780",paddingVertical:7},nav:{position:"absolute",left:12,right:12,bottom:14,height:68,borderRadius:23,backgroundColor:"#111116",borderWidth:1,borderColor:"#25252D",flexDirection:"row",justifyContent:"space-around",alignItems:"center"},navI:{alignItems:"center",gap:4},navT:{fontSize:9,fontWeight:"800"}});
